# Use the official image as a parent image
FROM ubuntu:22.04

# Update the system, install OpenSSH Server, and set up users
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y openssh-server gcc g++ cmake gdb && \
    rm -rf /var/lib/apt/lists/*

# Create user and set password for user and root user
RUN  useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 ubuntu && \
    echo 'ubuntu:password' | chpasswd && \
    echo 'root:password' | chpasswd

# Set up configuration for SSH
RUN mkdir /var/run/sshd && \
    sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    echo "export VISIBLE=now" >> /etc/profile

# Expose the SSH port
EXPOSE 22

# Run SSH
CMD ["/usr/sbin/sshd", "-D"]

# docker build -f .\Dockerfile-ubuntu -t ubuntu-ssh .
# docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -d -p 2222:22 ubuntu-ssh
# ssh-keygen -R [localhost]:2222; ssh ubuntu@localhost -p 2222
# gcclinaro, xtools !! 