# Use the official Raspberry Pi image as a parent image
FROM desktopcontainers/raspberrypi

# Update the sources list to use Debian Buster
RUN sed -i 's/stretch/buster/g' /etc/apt/sources.list

# Update the system and install OpenSSH Server
RUN apt-get update && apt-get upgrade -y --allow-unauthenticated && \
    apt-get install -y openssh-server gcc g++ --allow-unauthenticated && \
    rm -rf /var/lib/apt/lists/*

# Set up configuration for SSH
RUN [ ! -d /var/run/sshd ] && mkdir /var/run/sshd || true && \
    sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    echo "export VISIBLE=now" >> /etc/profile

# Copy hello_world_c directory to /home/pi/hello_world_c in the container
COPY /example_code/hello_world_c /home/pi/hello_world_c


# Expose the SSH port
EXPOSE 22

# Run SSH
CMD ["/usr/sbin/sshd", "-D"]
# docker build -f Dockerfile-dockerpi -t dockerpi-ssh .
# docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -d -p 2222:22 dockerpi-ssh
# ssh-keygen -R [localhost]:2222; ssh pi@localhost -p 2222