version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  web:
    image: php:7.4-apache
    ports:
      - "8081:80"
    volumes:
      - ./php-app:/var/www/html
    depends_on:
      - db
    command: bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge