version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network_2

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/root/redis
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    networks:
      - my_network_2
    command: bash -c "redis-server --requirepass password"

  web:
    image: php:7.4-apache
    ports:
      - "8082:80"
    volumes:
      - ./sites:/var/www/html
    depends_on:
      - db
    command: bash -c "docker-php-ext-install pdo pdo_mysql && pecl install redis && docker-php-ext-enable redis && apache2-foreground"
    networks:
      - my_network_2

volumes:
  db_data:
  redis_data:

networks:
  my_network_2:
    driver: bridge